[workspace]
resolver = "3"

[workspace.package]
version = "1.0.1"
edition = "2024"
rust-version = "1.91.0"
license = "Apache-2.0 OR MIT"
homepage = "https://github.com/DenisGorbachev/fjall-cli"
repository = "https://github.com/DenisGorbachev/fjall-cli"
keywords = []
categories = []
exclude = [
    ".*",
    "*.local.*",
    "doc/dev",
    "specs",
    "AGENTS.ts",
    "CargoMetadata.ts",
    "README.ts",
    "AGENTS*.md",
    "CLAUDE*.md",
    "deno.lock",
    "deno.json",
    "commitlint.config.mjs",
    "fnox.toml",
    "mise.toml",
    "rumdl.toml",
    "rustfmt.toml",
    ".yolobox"
]

[workspace.metadata.details]
name = "fjall-cli"
title = "CLI for Fjall database"
readme = { generate = true }

[workspace.lints.rust]
redundant_imports = "deny"
unused_import_braces = "deny"
# unused_qualifications must not be "deny" because our code style has multiple `use Foo::*;`, and some macros (derive_more::Display, strum::Display, strum::EnumString) produce code with full qualifications
# unused_qualifications = "deny"

[workspace.lints.clippy]
absolute_paths = "deny"
arithmetic_side_effects = "deny"

[package]
name = "fjall-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "CLI for Fjall database"
license.workspace = true
homepage.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
exclude.workspace = true

[package.metadata.details]
title = "CLI for Fjall database"

[lints]
workspace = true

[[bin]]
name = "fjall"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5.11", features = ["derive", "env"] }
errgonomic = { version = "0.5.3" }
fjall = "3.0.2"
hex = "0.4.3"
strum = { version = "0.27.2", features = ["derive"] }
thiserror = "2.0.17"
tokio = { version = "1.39.2", features = ["macros", "fs", "net", "rt", "rt-multi-thread"] }

[dev-dependencies]
tempdir = "0.3.7"
xshell = "0.3.0-pre.2"
