[package]
name = "fjall-cli"
version = "1.0.1"
edition = "2024"
rust-version = "1.91.0"
description = "CLI for Fjall database"
license = "Apache-2.0 OR MIT"
homepage = "https://github.com/DenisGorbachev/fjall-cli"
repository = "https://github.com/DenisGorbachev/fjall-cli"
readme = "README.md"
keywords = []
categories = []
exclude = [
    ".*",
    "*.local.*",
    "doc/dev",
    "specs",
    "README.ts",
    "AGENTS*.md",
    "CLAUDE*.md",
    "deno.json",
    "commitlint.config.mjs",
    "lefthook.yml",
    "mise.toml",
    "rumdl.toml",
    "rustfmt.toml",
    "yolobox"
]

[package.metadata.details]
title = "CLI for Fjall database"
tagline = ""
summary = ""
announcement = ""
readme = { generate = true }

[[bin]]
name = "fjall"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5.11", features = ["derive", "env"] }
errgonomic = { version = "0.5.0" }
fjall = "3.0.2"
hex = "0.4.3"
strum = { version = "0.27.2", features = ["derive"] }
thiserror = "2.0.17"
tokio = { version = "1.39.2", features = ["macros", "fs", "net", "rt", "rt-multi-thread"] }

[dev-dependencies]
tempdir = "0.3.7"
xshell = "0.3.0-pre.2"
